// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzLf5AdYBXK5LGl9O0I9KR2nqo3ddZaaQ',
    appId: '1:560407368750:web:1e709ff0a2f88261e6bbbf',
    messagingSenderId: '560407368750',
    projectId: 'undercovergame-ae096',
    authDomain: 'undercovergame-ae096.firebaseapp.com',
    storageBucket: 'undercovergame-ae096.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA76dxo3iW81Ix9l7KjcSPZxRLKLAtILAQ',
    appId: '1:560407368750:android:f344688034b89c91e6bbbf',
    messagingSenderId: '560407368750',
    projectId: 'undercovergame-ae096',
    storageBucket: 'undercovergame-ae096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBydgz-iTjcLSHuFMy-GInwyYEd1oj5yBY',
    appId: '1:560407368750:ios:daff2726ccc95392e6bbbf',
    messagingSenderId: '560407368750',
    projectId: 'undercovergame-ae096',
    storageBucket: 'undercovergame-ae096.appspot.com',
    iosBundleId: 'com.undercover.undercoverleague.undercoverleague',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBydgz-iTjcLSHuFMy-GInwyYEd1oj5yBY',
    appId: '1:560407368750:ios:daff2726ccc95392e6bbbf',
    messagingSenderId: '560407368750',
    projectId: 'undercovergame-ae096',
    storageBucket: 'undercovergame-ae096.appspot.com',
    iosBundleId: 'com.undercover.undercoverleague.undercoverleague',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzLf5AdYBXK5LGl9O0I9KR2nqo3ddZaaQ',
    appId: '1:560407368750:web:2435d6aff0320d6ee6bbbf',
    messagingSenderId: '560407368750',
    projectId: 'undercovergame-ae096',
    authDomain: 'undercovergame-ae096.firebaseapp.com',
    storageBucket: 'undercovergame-ae096.appspot.com',
  );
}
